Fixed uncaught exception when XRefMap is invalid.
bonsai-rx/bonsai pull request #1785
Opened 2024-05-09 21:37 UTC by PathogenDavid

The deserialization exceptions were making it to the generic unhandled exception dialog due to the relevant catch clause looking for `SystemException`.

`SystemException` (and its complement `ApplicationException`) is a bit of a failed experiment from .NET Framework 1. It's no longer used for new `System.*` exceptions, and even before .NET Core it was applied very inconsistently. IMO the line between exceptions in the `System` namespace and exceptions outside of it is basically meaningless and very fuzzy regardless.

As such this PR increases the scope to just plain `Exception`.

------------------

This still would have resulted in very vague low-level errors reaching the end user, so I introduced `DocumentationException` to denote specific errors when parsing the XRefMap.

When one XRefMap fails due to a 404 and another fails due to a `DocumentationException`, the `DocumentationException` takes priority.

------------------

Here is the error that occurs when the documentation server responds with something other than an XRefMap:

![image](https://github.com/bonsai-rx/bonsai/assets/278957/12e0de07-3e48-408b-b1f2-d8bc6e9efe3d)

And here's the error that occurs when the documentation server responds with something that claims to be an XRefMap but isn't unusable:

![image](https://github.com/bonsai-rx/bonsai/assets/278957/1d73d2c1-cc6a-4167-819f-145c4e25f3d8)

Fixes https://github.com/bonsai-rx/bonsai/issues/1507

2024-05-09 22:08 UTC, glopesdev requested changes
This looks great, thanks! Just very minor style tweaks for consistency with current code, looking forward to drafting together a style guide for modern .NET.

2024-05-09 22:08 UTC, glopesdev commented on Bonsai.Editor/DocumentationHelper.cs
> +            { throw new DocumentationException("The cross-reference map returned by the documentation server is malformed.", ex); }
```suggestion
            try { xrefmap = deserializer.Deserialize<XRefMap>(reader); }
            catch (YamlException ex)
            {
                throw new DocumentationException("The cross-reference map returned by the documentation server is malformed.", ex);
            }
```

For same style reasons as above.

2024-05-10 00:02 UTC, PathogenDavid commented
Fixed!

> looking forward to drafting together a style guide for modern .NET.

I'll definitely have strong opinions about your `try { SingleLine(); }` habit. It breaks auto-formatting 😅

I can cope for now though.

2024-05-10 00:05 UTC, glopesdev approved these changes

2024-05-10 00:06 UTC, merged